//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WPSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WPSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string AlbumColumn {
            get {
                return ResourceManager.GetString("AlbumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string AllEpisodesText {
            get {
                return ResourceManager.GetString("AllEpisodesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string AllUnplayedText {
            get {
                return ResourceManager.GetString("AllUnplayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string AppAlreadyRunningMessage {
            get {
                return ResourceManager.GetString("AppAlreadyRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string AppAlreadyRunningTitle {
            get {
                return ResourceManager.GetString("AppAlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string AppSettingsTitleText {
            get {
                return ResourceManager.GetString("AppSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string AppSettingSyncSourceWindowsLibraries {
            get {
                return ResourceManager.GetString("AppSettingSyncSourceWindowsLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string AppsStorageText {
            get {
                return ResourceManager.GetString("AppsStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string ArtistColumn {
            get {
                return ResourceManager.GetString("ArtistColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string ArtistsText {
            get {
                return ResourceManager.GetString("ArtistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string CancellingSyncText {
            get {
                return ResourceManager.GetString("CancellingSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string CancelSyncText {
            get {
                return ResourceManager.GetString("CancelSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string CancelSyncTitle {
            get {
                return ResourceManager.GetString("CancelSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddddd.
        /// </summary>
        public static string CantSwitchSyncSourceText {
            get {
                return ResourceManager.GetString("CantSwitchSyncSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string CantSwitchSyncSourceTitle {
            get {
                return ResourceManager.GetString("CantSwitchSyncSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string ConnectingToDeviceMessage {
            get {
                return ResourceManager.GetString("ConnectingToDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string DeviceNameText {
            get {
                return ResourceManager.GetString("DeviceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string DeviceSettingOptimizationQuality {
            get {
                return ResourceManager.GetString("DeviceSettingOptimizationQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string DeviceSettingsTitleText {
            get {
                return ResourceManager.GetString("DeviceSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string DisconnectedHeader {
            get {
                return ResourceManager.GetString("DisconnectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string DisconnectedLinkText {
            get {
                return ResourceManager.GetString("DisconnectedLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddd.
        /// </summary>
        public static string DisconnectedText {
            get {
                return ResourceManager.GetString("DisconnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ewrewererer.
        /// </summary>
        public static string DocumentsText {
            get {
                return ResourceManager.GetString("DocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string DrmWarningText {
            get {
                return ResourceManager.GetString("DrmWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string DurationColumn {
            get {
                return ResourceManager.GetString("DurationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd.
        /// </summary>
        public static string EnableSyncToolTipText {
            get {
                return ResourceManager.GetString("EnableSyncToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string EraseContentButtonText {
            get {
                return ResourceManager.GetString("EraseContentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string EraseContentText {
            get {
                return ResourceManager.GetString("EraseContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd.
        /// </summary>
        public static string EraseContentWarningText {
            get {
                return ResourceManager.GetString("EraseContentWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddwweewq.
        /// </summary>
        public static string EraseContentWarningTitle {
            get {
                return ResourceManager.GetString("EraseContentWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeeeee.
        /// </summary>
        public static string ErrCopyToPc {
            get {
                return ResourceManager.GetString("ErrCopyToPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dasdsaadss.
        /// </summary>
        public static string ErrCopyToPhone {
            get {
                return ResourceManager.GetString("ErrCopyToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eeweqewwqe.
        /// </summary>
        public static string ErrDeleteFromPhone {
            get {
                return ResourceManager.GetString("ErrDeleteFromPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddwweqweq.
        /// </summary>
        public static string ErrFileSystemChange {
            get {
                return ResourceManager.GetString("ErrFileSystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wqeewqewqweq.
        /// </summary>
        public static string ErrLoadingCache {
            get {
                return ResourceManager.GetString("ErrLoadingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrTranscode.
        /// </summary>
        public static string ErrTranscode {
            get {
                return ResourceManager.GetString("ErrTranscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrUpdatePhone.
        /// </summary>
        public static string ErrUpdatePhone {
            get {
                return ResourceManager.GetString("ErrUpdatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrVerifyingFile.
        /// </summary>
        public static string ErrVerifyingFile {
            get {
                return ResourceManager.GetString("ErrVerifyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstConnectDeviceNameText.
        /// </summary>
        public static string FirstConnectDeviceNameText {
            get {
                return ResourceManager.GetString("FirstConnectDeviceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstConnectSettingsInfoText.
        /// </summary>
        public static string FirstConnectSettingsInfoText {
            get {
                return ResourceManager.GetString("FirstConnectSettingsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstConnectWelcomeSubText.
        /// </summary>
        public static string FirstConnectWelcomeSubText {
            get {
                return ResourceManager.GetString("FirstConnectWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstConnectWelcomeText.
        /// </summary>
        public static string FirstConnectWelcomeText {
            get {
                return ResourceManager.GetString("FirstConnectWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoldersText.
        /// </summary>
        public static string FoldersText {
            get {
                return ResourceManager.GetString("FoldersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgetDeviceWarningText.
        /// </summary>
        public static string ForgetDeviceWarningText {
            get {
                return ResourceManager.GetString("ForgetDeviceWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgetDeviceWarningTitle.
        /// </summary>
        public static string ForgetDeviceWarningTitle {
            get {
                return ResourceManager.GetString("ForgetDeviceWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgetPhoneFilesError.
        /// </summary>
        public static string ForgetPhoneFilesError {
            get {
                return ResourceManager.GetString("ForgetPhoneFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgetThisPhoneText.
        /// </summary>
        public static string ForgetThisPhoneText {
            get {
                return ResourceManager.GetString("ForgetThisPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Recent1EpisodeText {
            get {
                return ResourceManager.GetString("Recent1EpisodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Recent3EpisodeText {
            get {
                return ResourceManager.GetString("Recent3EpisodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Recent5EpisodeText {
            get {
                return ResourceManager.GetString("Recent5EpisodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string SyncRulesCorruptText {
            get {
                return ResourceManager.GetString("SyncRulesCorruptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string SyncSourceLabelText {
            get {
                return ResourceManager.GetString("SyncSourceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string SyncWithThisComputerText {
            get {
                return ResourceManager.GetString("SyncWithThisComputerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string Unplayed1Text {
            get {
                return ResourceManager.GetString("Unplayed1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdfdf.
        /// </summary>
        public static string Unplayed3Text {
            get {
                return ResourceManager.GetString("Unplayed3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Unplayed5Text {
            get {
                return ResourceManager.GetString("Unplayed5Text", resourceCulture);
            }
        }
    }
}
