//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDirectory.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicDirectory.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string CantSwitchSyncSourceText {
            get {
                return ResourceManager.GetString("CantSwitchSyncSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddfff.
        /// </summary>
        internal static string CantSwitchSyncSourceTitle {
            get {
                return ResourceManager.GetString("CantSwitchSyncSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsadsa.
        /// </summary>
        internal static string EraseContentWarningText {
            get {
                return ResourceManager.GetString("EraseContentWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadsadsa.
        /// </summary>
        internal static string EraseContentWarningTitle {
            get {
                return ResourceManager.GetString("EraseContentWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string iTunesMissingWillSwitchMessage {
            get {
                return ResourceManager.GetString("iTunesMissingWillSwitchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddfff.
        /// </summary>
        internal static string iTunesMissingWillSwitchTitle {
            get {
                return ResourceManager.GetString("iTunesMissingWillSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdddddd.
        /// </summary>
        internal static string MissingValueText {
            get {
                return ResourceManager.GetString("MissingValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sddddfff.
        /// </summary>
        internal static string PicturesTransferDirectoryFormat {
            get {
                return ResourceManager.GetString("PicturesTransferDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddddff.
        /// </summary>
        internal static string SwitchSyncSourceWarningText {
            get {
                return ResourceManager.GetString("SwitchSyncSourceWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fggg.
        /// </summary>
        internal static string SwitchSyncSourceWarningTitle {
            get {
                return ResourceManager.GetString("SwitchSyncSourceWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsadsasdaddd.
        /// </summary>
        internal static string SyncRulesCorruptText {
            get {
                return ResourceManager.GetString("SyncRulesCorruptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddff.
        /// </summary>
        internal static string ZmdbErrorText {
            get {
                return ResourceManager.GetString("ZmdbErrorText", resourceCulture);
            }
        }
    }
}
